Get a digital twin with properties
indykite/jarvis-sdk-python pull request #13
Opened 2022-05-06 15:01 UTC by dusan-kovacik-profiq

# Checklist

- [ ] `make test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](./doc/guides/commit-message.md#commit-message-guidelines)

## Affected core subsystem(s)

## Description of change

2022-05-16 07:20 UTC, arxeiss approved these changes
My Python knowledge is less than low, so rather get approval from someone more skilled

2022-05-23 07:54 UTC, kilimandzsaro requested changes
Can you please add a github action to run the unit tests for each pull request?

2022-05-23 07:54 UTC, kilimandzsaro commented on jarvis_sdk/cmd/_get_digital_twin.py
> +    dt_result = {}
These few lines are the same as the lines from 67. Do you think if it can be as a "global" function and just call it here? (If there is/will be another place using the same code snipet, then probably would be good to make it a function which can be called from anywhere)

2022-05-24 08:17 UTC, dusan-kovacik-profiq commented
> Can you please add a github action to run the unit tests for each pull request?

@kilimandzsaro Would you be OK with that if I add the github action in a different PR? I will ask Martin P. about it because he was the one who configured it in other repositories as well.

2022-05-24 08:18 UTC, dusan-kovacik-profiq commented on jarvis_sdk/cmd/_get_digital_twin.py
> +    dt_result = {}
Yes, I've created `deserialize_digital_twin_with_token_info` function for that.

2022-05-25 06:10 UTC, bakkelim approved these changes

2022-05-25 06:56 UTC, merged