ci: enable deployment analytics github action
indykite/jarvis-sdk-python pull request #23
Opened 2022-06-14 12:03 UTC by martasd

# Checklist

- [ ] `make test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](./doc/guides/commit-message.md#commit-message-guidelines)

## Affected core subsystem(s)

## Description of change

2022-06-17 10:23 UTC, maprokes requested changes

2022-06-17 10:23 UTC, maprokes commented on .github/workflows/release.yaml
> +        uses: actions/checkout@v3
@martasd I just noticed that you are missing `if: ${{ always() }}` in the setup steps. The **Save Deployment Metadata** will fail

2022-06-17 11:38 UTC, martasd commented on .github/workflows/release.yaml
> +        uses: actions/checkout@v3
@maprokes In this case, we want to handle the case when the **Release SDK to pypi repository** step fails, right? If so, this check should go right after that step, shouldn't it?

2022-06-27 13:43 UTC, maprokes approved these changes

2022-06-27 13:49 UTC, merged