feat: add config methods 2798
indykite/jarvis-sdk-python pull request #87
Opened 2022-10-10 09:12 UTC by oceane-sailorin

# Checklist

- [ ] `make test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added

## Affected core subsystem(s)

## Description of change

2022-10-11 15:07 UTC, kilimandzsaro requested changes

2022-10-11 15:07 UTC, kilimandzsaro commented on tests/test_get_digital_twin.py
> +    response = client.get_digital_twin("6cdf1133-ba32-4dbb-a977-60b0d5d5e713", "696e6479-6b69-4465-8000-030f00000001", [])
Since you removed the `tenant_id` variable from this line, does the line 55 (`tenant_id = data.get_tenant()`) needed?

2022-10-12 10:52 UTC, oceane-sailorin commented on jarvis_sdk/api.py
> +    customer_name_parser.add_argument("customer_name", help="Customer name")
precision added

2022-10-12 10:52 UTC, oceane-sailorin commented on jarvis_sdk/api.py
> +    app_space_id_parser.add_argument("app_space_id", help="App Space id")
precision added

2022-10-12 10:52 UTC, oceane-sailorin commented on jarvis_sdk/api.py
> +    app_space_name_parser.add_argument("app_space_name", help="App Space name")
precision added

2022-10-12 10:52 UTC, oceane-sailorin commented on jarvis_sdk/api.py
> +    app_space_name_parser.add_argument("customer_id", help="Customer Id")
precision added

2022-10-12 10:52 UTC, oceane-sailorin commented on tests/test_get_digital_twin.py
> +    response = client.get_digital_twin("6cdf1133-ba32-4dbb-a977-60b0d5d5e713", "696e6479-6b69-4465-8000-030f00000001", [])
change made

2022-10-12 11:12 UTC, oceane-sailorin commented
too many commits

2022-10-12 11:12 UTC, closed without merging